#!/usr/bin/env python3
"""
05_roi_placement_viewer.py — Interactive 3D HTML viewer for self/nonself atlas QC

Visually verifies that each ROI in the self atlas (37 ROIs, Qin et al. 2020)
and nonself atlas (~316 ROIs, Glasser parcellation) is anatomically placed
correctly. Also produces TSV tables with centroid coordinates and voxel counts,
and flags any ROIs outside the expected voxel-count range.

RUN ON SERVER:
  conda activate fmri
  cd /BICNAS2/group-northoff/jkokino/codes/har_med_codes
  python 99_QC/03_acw_qc/scripts/05_roi_placement_viewer.py

After completion, transfer outputs to local machine:
  scp jkokino@10.156.156.21:.../99_QC/03_acw_qc/figures/self_atlas_viewer.html    <local>/
  scp jkokino@10.156.156.21:.../99_QC/03_acw_qc/figures/nonself_atlas_viewer.html <local>/
  scp jkokino@10.156.156.21:.../99_QC/03_acw_qc/results/self_atlas_summary.tsv    <local>/
  scp jkokino@10.156.156.21:.../99_QC/03_acw_qc/results/nonself_atlas_summary.tsv <local>/
"""

import sys
import numpy as np
import pandas as pd
import nibabel as nib
from pathlib import Path
from nilearn import plotting, datasets

# ── Repo root (script at 99_QC/03_acw_qc/scripts/) ──────────────────────────
REPO_ROOT = Path(__file__).resolve().parents[3]

# ── Input paths ───────────────────────────────────────────────────────────────
ATLAS_DIR = REPO_ROOT / "02_timeseries_extraction" / "results" / "atlases"

SELF_ATLAS      = ATLAS_DIR / "self_atlas_1mm.nii.gz"
NONSELF_ATLAS   = ATLAS_DIR / "nonself_atlas_1mm.nii.gz"
SELF_LABELS     = ATLAS_DIR / "self_labels.txt"
NONSELF_LABELS  = ATLAS_DIR / "glasser_coordinates_nonself_clean.txt"

# MNI 1mm template: server path preferred; nilearn built-in as fallback
MNI_SERVER = Path("/home/jkokino/meditation_project/templates/MNI/mni_icbm152_1mm.nii")

# ── Output paths ──────────────────────────────────────────────────────────────
FIG_DIR     = REPO_ROOT / "99_QC" / "03_acw_qc" / "figures"
RESULTS_DIR = REPO_ROOT / "99_QC" / "03_acw_qc" / "results"

SELF_HTML    = FIG_DIR / "self_atlas_viewer.html"
NONSELF_HTML = FIG_DIR / "nonself_atlas_viewer.html"
SELF_TSV     = RESULTS_DIR / "self_atlas_summary.tsv"
NONSELF_TSV  = RESULTS_DIR / "nonself_atlas_summary.tsv"

# ── Sanity thresholds (4mm-radius sphere at 1mm resolution) ──────────────────
# Perfect sphere volume = (4/3)π(4)³ ≈ 268 voxels; after voxel discretization
# the typical count is ~257. ROIs near brain boundaries (e.g. V1, temporal
# poles) can be as low as ~150. Out-of-brain or severely clipped ROIs drop
# below ~100; overlapping ROIs would show as 0.
VOXEL_MIN = 100   # below this → likely out-of-brain or badly clipped
VOXEL_MAX = 300   # above this → impossible for a 4mm sphere, suggests atlas bug

# ── Check required inputs ─────────────────────────────────────────────────────
missing = [f for f in [SELF_ATLAS, NONSELF_ATLAS, SELF_LABELS, NONSELF_LABELS]
           if not f.exists()]
if missing:
    for m in missing:
        print(f"ERROR: Missing required input: {m}", file=sys.stderr)
    sys.exit(1)

FIG_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# ── MNI template ──────────────────────────────────────────────────────────────
if MNI_SERVER.exists():
    mni_img = nib.load(str(MNI_SERVER))
    print(f"MNI template: {MNI_SERVER}")
else:
    mni_img = datasets.load_mni152_template(resolution=1)
    print("MNI template: nilearn built-in (1mm)")


# ── Label loaders ─────────────────────────────────────────────────────────────
def load_self_labels():
    """
    self_labels.txt: space-separated 'roi_num roi_name', no header.
    Generated by 01_create_self_atlas.sh via awk '{print $1, $2}'.
    """
    rows = []
    with open(SELF_LABELS) as fh:
        for line in fh:
            parts = line.strip().split()
            if len(parts) >= 2:
                rows.append({"roi_id": int(parts[0]), "roi_name": parts[1]})
    return pd.DataFrame(rows)


def load_nonself_labels():
    """
    glasser_coordinates_nonself_clean.txt: TSV with header ROI_Number/ROI_Name/X/Y/Z.
    ROI_Number values are the original Glasser parcel numbers (used as voxel
    values in nonself_atlas_1mm.nii.gz by 3dUndump).
    """
    df = pd.read_csv(NONSELF_LABELS, sep="\t")
    df = df.rename(columns={"ROI_Number": "roi_id", "ROI_Name": "roi_name"})
    return df[["roi_id", "roi_name"]]


# ── Core computation ──────────────────────────────────────────────────────────
def compute_roi_summary(atlas_img, labels_df):
    """
    For each ROI, compute centroid (MNI mm) and voxel count from atlas_img.
    Returns DataFrame: roi_id, roi_name, x, y, z, n_voxels.
    """
    data   = atlas_img.get_fdata()
    affine = atlas_img.affine
    rows   = []

    for _, row in labels_df.iterrows():
        roi_id = int(row["roi_id"])
        name   = str(row["roi_name"])
        mask   = data == roi_id
        n_vox  = int(mask.sum())

        if n_vox == 0:
            print(f"  WARNING: ROI {roi_id} ({name}) — 0 voxels in atlas image")
            rows.append({"roi_id": roi_id, "roi_name": name,
                         "x": np.nan, "y": np.nan, "z": np.nan, "n_voxels": 0})
            continue

        # Centroid in voxel space → MNI mm via affine
        vox_ijk      = np.array(np.where(mask), dtype=float)  # (3, n_vox)
        centroid_vox = vox_ijk.mean(axis=1)                   # (3,)
        centroid_mni = affine @ np.append(centroid_vox, 1.0)

        rows.append({
            "roi_id":   roi_id,
            "roi_name": name,
            "x":        round(float(centroid_mni[0]), 1),
            "y":        round(float(centroid_mni[1]), 1),
            "z":        round(float(centroid_mni[2]), 1),
            "n_voxels": n_vox,
        })

    return pd.DataFrame(rows, columns=["roi_id", "roi_name", "x", "y", "z", "n_voxels"])


def flag_anomalous(summary_df, atlas_name):
    """Print ROIs with voxel count outside [VOXEL_MIN, VOXEL_MAX]."""
    flagged = summary_df[
        (summary_df["n_voxels"] < VOXEL_MIN) | (summary_df["n_voxels"] > VOXEL_MAX)
    ]
    if flagged.empty:
        print(f"  All {len(summary_df)} {atlas_name} ROIs within expected range "
              f"[{VOXEL_MIN}, {VOXEL_MAX}] voxels.")
    else:
        print(f"\n  !!! {atlas_name}: {len(flagged)} ROIs with anomalous voxel counts "
              f"(possible out-of-brain placement or atlas overlap):")
        for _, r in flagged.iterrows():
            tag = "TOO FEW" if r["n_voxels"] < VOXEL_MIN else "TOO MANY"
            print(f"    [{tag}]  ROI {int(r['roi_id']):4d}  "
                  f"{r['roi_name']:<40}  {int(r['n_voxels'])} voxels")


# ── Self atlas ────────────────────────────────────────────────────────────────
print("\n=== Self atlas ===")
self_img    = nib.load(str(SELF_ATLAS))
self_labels = load_self_labels()
print(f"  Atlas:  {SELF_ATLAS.name}  shape={self_img.shape}")
print(f"  Labels: {len(self_labels)} ROIs")

self_summary = compute_roi_summary(self_img, self_labels)
flag_anomalous(self_summary, "self")
self_summary.to_csv(SELF_TSV, sep="\t", index=False, float_format="%.1f")
print(f"  Summary TSV → {SELF_TSV}")

self_view = plotting.view_img(
    self_img,
    bg_img=mni_img,
    cmap="tab20",
    symmetric_cmap=False,
    vmin=0.5,
    vmax=float(len(self_labels)) + 0.5,
    threshold=0.5,
    title="Self atlas — 37 ROIs (Qin et al. 2020)",
    colorbar=True,
)
self_view.save_as_html(str(SELF_HTML))
print(f"  Interactive viewer → {SELF_HTML}")


# ── Nonself atlas ─────────────────────────────────────────────────────────────
print("\n=== Nonself atlas ===")
nonself_img    = nib.load(str(NONSELF_ATLAS))
nonself_labels = load_nonself_labels()
print(f"  Atlas:  {NONSELF_ATLAS.name}  shape={nonself_img.shape}")
print(f"  Labels: {len(nonself_labels)} ROIs")

nonself_summary = compute_roi_summary(nonself_img, nonself_labels)
flag_anomalous(nonself_summary, "nonself")
nonself_summary.to_csv(NONSELF_TSV, sep="\t", index=False, float_format="%.1f")
print(f"  Summary TSV → {NONSELF_TSV}")

# vmax from atlas image because nonself ROI numbers are original Glasser
# parcel IDs (not sequential 1-N), so the max value may exceed len(labels)
nonself_vmax = float(nonself_img.get_fdata().max()) + 0.5

nonself_view = plotting.view_img(
    nonself_img,
    bg_img=mni_img,
    cmap="tab20",
    symmetric_cmap=False,
    vmin=0.5,
    vmax=nonself_vmax,
    threshold=0.5,
    title=f"Nonself atlas — {len(nonself_labels)} ROIs (Glasser parcellation)",
    colorbar=True,
)
nonself_view.save_as_html(str(NONSELF_HTML))
print(f"  Interactive viewer → {NONSELF_HTML}")


# ── Final summary ─────────────────────────────────────────────────────────────
print("\n=== Summary ===")
for name, df in [("Self   ", self_summary), ("Nonself", nonself_summary)]:
    valid = df[df["n_voxels"] > 0]
    print(f"  {name}: {len(df)} ROIs — "
          f"voxels/ROI mean={valid['n_voxels'].mean():.1f}, "
          f"min={valid['n_voxels'].min()}, "
          f"max={valid['n_voxels'].max()}")

print()
print("Outputs:")
for p in [SELF_HTML, NONSELF_HTML, SELF_TSV, NONSELF_TSV]:
    print(f"  {p}")
